### ISSUE TITLE
Title not updated

### ISSUE THREAD

**Issue by NoyChan** [DylanVann/ant-design-draggable-modal#5]
If you change the title prop, the modal didn't show the changed title unless you make a drag

**Comment by DylanVann** [comment]
Thanks for reporting!

It's due to sloppy usage of hooks. Fixed here - https://github.com/DylanVann/ant-design-draggable-modal/commit/fc5539f078e51f770b222fe22f5e717d6167708b

The fix is available in `v0.0.13`.

I've added ESLint with `eslint-plugin-react-hooks` to prevent any other issues like this:

![Screen Shot 2019-03-19 at 1 00 37 PM](https://user-images.githubusercontent.com/1537615/54626715-1ca22580-4a48-11e9-86a9-d478a9df3a5c.png)
